
#define IDI_ICON1  1
#define IDI_ICON2  2
#define IDI_ICON3  3

#define IDD_ABOUTBOX    100
#define IDD_OPTIONBOX   101
                            /* strings */
#define IDS_APPNAME    64
#define IDS_TITLE      65
#define IDS_ININAME    66
#define IDS_WINCAP     67
#define IDS_ERRNOCLEX  68
#define IDS_ERRMEM     69
#define IDS_ERRCLASS   70
#define IDS_ERRREG     71
                             /* IDs menus */
#define IDM_MENU1       51
                             /* shared IDs */
#define ID_WARNING1    41
                             /* IDs main */
#define ID_ABOUT       51
#define ID_OPTION      52
#define ID_EXIT        53
#define ID_SAVEAS      54
#define ID_HELP        56
#define ID_INTVCHANGE  57
#define ID_TEST        58
#define ID_CLEAR       61
#define ID_MAINLB      62
                             /* IDs option box */
#define ID_INTERVAL    53
#define ID_SAVEOPT     54
#define ID_DBGOPT      55
#define ID_INTREG      56
#define ID_BREAK       57
#define ID_UNKNOWN     70
                             /* IDs aboutbox */
#define ID_CPYRT       51
                             /* IDs registerbox */
#define ID_LISTREG     51

