#define IDI_ICON1     100    // ID icon
#define IDA_ACCEL1    101    /* IDs accelerators */
#define IDD_ABOUTBOX  102    /* IDs dialogboxen */
#define IDD_OPTIONBOX 103
#define IDD_REGBOX    104
                             /* IDs menu resourcen */
#define IDR_MENU1      105
                             /* globale message (bspw. ueber createmessage) */
#define ID_WARNING1    106
                             /* IDs main */
#define IDM_ABOUT       107
#define IDM_OPTION      108
#define IDM_EXIT        109
#define IDM_TYPECHANGE  110
#define IDM_STARTSTOP   111
#define IDM_HELP        112
#define IDM_INTVCHANGE  113
#define IDM_TEST        114
#define IDM_REGSOUT     115
#define IDM_SAVE        116
#define IDM_CLEAR       117
#define IDM_MAINLB      118
                             /* IDs option box */
#define IDC_TYPEP       119
#define IDC_TYPER       120
#define IDC_TYPENH      121

#define IDC_INTERVAL    122
#define IDC_SAVEOPT     123
#define IDC_CARRY       124
                             /* IDs aboutbox */
#define IDC_CPYRT       125
                             /* IDs registerbox */
#define IDC_LISTREG     126
                             /* IDs filebox */
#define IDC_LISTFILE    127
#define IDC_UEB1FILE    128
#define IDC_NEWFILE     129


                             /* IDs strings */
#define IDS_APPNAME    64
#define IDS_TITLE      65
#define IDS_DATE       66
#define IDS_START      67
#define IDS_STOP       68
#define IDS_ERRSTART   69
#define IDS_ERRSTOP    70
#define IDS_ERRNODOS   71
#define IDS_ERRNOCLEX  72
#define IDS_REGUEB     73
#define IDS_ERRPMON    74
#define IDS_ERRRMON    75
#define IDS_ERRNHMON   76
#define IDS_RMSWITCH   77
#define IDS_PMSWITCH   78
#define IDS_NHSWITCH   79
#define IDS_RMSTR      80
#define IDS_PMSTR      81
#define IDS_NHSTR      82
#define IDS_ININAME    83
#define IDS_INACTIV    84
#define IDS_WINCAP     85
#define IDS_ERRCLASS   86
#define IDS_ERRDOSMEM  87
