
;--- this include is for assembler and resource compiler
;*** all resource ids in decimal!

;/*
IDR_MENU1    equ 2
IDI_ICON1    equ 4
IDA_ACCEL1   equ 5

IDM_EXIT   		equ 1000
IDM_ALLOC1		equ 1001
IDM_ALLOC2		equ 1002
IDM_ALLOC3		equ 1003
IDM_ALLOC4		equ 1004
IDM_DEALLOC		equ 1005
IDM_STATUS		equ 1006

comment `
;*/

#define IDR_MENU1	2
#define IDI_ICON1	4
#define IDA_ACCEL1	5
#define IDM_EXIT	1000
#define IDM_ALLOC1	1001
#define IDM_ALLOC2	1002
#define IDM_ALLOC3	1003
#define IDM_ALLOC4	1004
#define IDM_DEALLOC	1005
#define IDM_STATUS	1006

;/* ` */
